### ISSUE TITLE
api-key support

### ISSUE THREAD

**Issue by svenha** [ThomasHintz/chicken-scheme-send-grid#1]
The old method with api_key and api_user is discontinued in November, see e.g. https://sendgrid.com/docs/for-developers/sending-email/upgrade-your-authentication-method-to-api-keys/
Do you plan to support the new api key method (via a http header)?

**Comment by ThomasHintz** [comment]
Thanks for letting me know. I was unaware of that. I will look into it. 
Do you depend on the SendGrid chicken scheme library?

**Comment by svenha** [comment]
If you have no time to fix the Chicken egg, no problem. (I will implement a simple solution using curl, in this case.) Just wanted to avoid duplicate work, if you are planning to update your nice Chicken egg anyway :-)

**Comment by ThomasHintz** [comment]
Well I should fix it. I might use it again some time. :) Just wanted to 
know how much of a deadline it was haha. I have it on my calendar to 
work on a fix for it so hopefully that will happen soon.

**Comment by ThomasHintz** [comment]
So the documentation mentions API keys for the version of the API I'm using but in my testing they don't appear to work. I'm assuming I need to update to the newer API version which looks straightforward and that's my plan.

**Comment by ThomasHintz** [comment]
Hi @svenha,

I've just released version 3.0.0 of the send-grid library. It should be available soon when it hits the CHICKEN egg mirror. This version adds backwards compatible support for version 3 of the send grid API. I've added a new parameter `api-version` that allows you to switch to version `"3"`. When version 2 is turned off by SendGrid I plan to release a new version of the library that makes version 3 the default.

The wiki page for the egg should be up-to-date. Please feel free to let me know if you experience issues.

All the best,
Thomas Hintz

**Comment by svenha** [comment]
Hi @ThomasHintz.

Thanks for the new version. I tested it with `api-version 3`, with and without attachments. Works perfectly.
I edited http://wiki.call-cc.org/eggref/4/send-grid slightly (the files: example).

Ciao
Sven
